development:
  adapter: postgresql
  encoding: unicode
  database: tv_app_development
  pool: 5
  username: alexguo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tv_app_test
  pool: 5
  username: alexguo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tv_app_production
  pool: 5
  username: alexguo
  password: