# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02a83e64e02ba74f03b0c7e2acb966b090ba83f504227b52f6b7c86c2fc97705bf6a5fbc289e6b81f7b364373ed144d698042a2fe00bd5c4ff9028b71ecebb5
  tmdb_key: 5c4da488f4095baec6e3e44fcbfc094a

test:
  secret_key_base: e3d8e69979bdecddbf315e46d935b171fdd28674a6a277b6c7ced6a464b66bdd678e3fd0e281ba5d08818f0b2d5bf018eb3828bff22899b36fb7474653950ec4
  tmdb_key: 5c4da488f4095baec6e3e44fcbfc094a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tmdb_key: 5c4da488f4095baec6e3e44fcbfc094a
